#!/usr/bin/env python3
"""fw42-dossier — the triptych machine (the fourth weld).

After ring 41 the day-0 protocol still ran as TWO commands plus manual
assembly: fw40's `chain` welded exam+identify+score (readings 1 and 2),
but the third reading — fw41's novelty scan — ran BESIDE the chain, its
JSON landing in a separate file that no instrument ever confronted with
the scoreline. Nothing answered the only question that matters when
three machines read one image: DO THEY TELL THE SAME STORY? This
instrument closes that seam and adds the layer none of the three
readings has: the coherence verdict.

    dossier = oracle (fw35, welded 38+39+40) + judge (39) + detector (41)
              + THE COHERENCE LAYER (42)

Four laws, each a gate family:

  L1 COMPLETENESS  every reading is present and provenance-stamped
                   (instrument + ring); a reading that cannot run is a
                   loud refusal (exit 2), never a silent block.
  L2 COHERENCE     every non-hit oracle row is cross-referenced with the
                   detector through the blind-spot map (below) and gets
                   a coupling class; the identity verdict is coupled to
                   the detector total; contradiction = refusal.
  L3 CALIBRATION   on a known rung the dossier must equal the clean
                   profile registered in vendor-dossier-register.json;
                   byte-identity (sha hit) forces the scoreline onto the
                   scorelines-register ceiling — any deviation is an
                   instrument disagreement and is refused.
  L4 SEPARATION    day-0 and release-41 targets never mix (inherited
                   from the fw40 weld; the dossier echoes it).

THE BLIND-SPOT MAP (axis_map). For each of the 26 registered predictions
the map names the detector axis that could CONFIRM a miss (strength
`set`: the axis diffs sets, direct evidence; `co`: co-travel, indirect),
or declares the row BLIND with the reason. The measured result is itself
a finding: 9 of 26 predictions are invisible to the detector (IFR
facade, varstore, PSP bodies, AOD SSDT revisions, rom size) — on those
rows a miss can never be confirmed by the third reading, and the
operator lens (fw38's manual slots) is the only witness. The map is
validated against the live oracle register (gate R1: exact coverage of
P-01..P-26) and frozen into vendor-dossier-register.json.

Coupling classes (oracle rows): aligned (hit), na, blind (miss/partial
on a blind row), confirmed (miss/partial + detector entries on the same
axis — the detector explains the miss), bare (miss/partial, no detector
entry — lens or measurement error, or a divergence deeper than the
detector can name), identity (P-18 rides on identity_coupling).

Identity coupling: known-clean (known-release + zero unregistered),
coherent-foreign (no-match + unregistered content — the OVMF/TUF
profile), suspicious (no-match + zero unregistered — the judge sees
differences the detector cannot name: check the blind axes),
refused-contradiction (known-release + unregistered content —
impossible by the coverage proof I1/I2 unless registers drifted;
exit 2).

Profiles (claim-free, derived): clean / stranger / suspicious / refused,
plus clean-pair / event-pair in pair mode. The H3 question is
deliberately NOT a profile — it is the P-18 row and the identity
verdict, already in the dossier; the instrument does not know what the
16/09 image is supposed to be.

Modes: dossier <image> (the ONE day-0 command, lenses pass through),
dossier-pair <old> <new> (the release-41 command: exam_pair + identify
+ weld + score + novelty + pair coherence — brand-new species are
births that even the register universe cannot claim), clean <rung>
(the live calibration target), register (print the frozen dossier
register), selftest [--no-live], manifest.

The new register lab/vendor-dossier-register.json (generated live by
scripts/ring42_artifact.py, generated by THIS instrument's gates for
freshness) freezes: the blind-spot map, the clean dossier of all nine
rungs, the foreign dossier (OVMF), the same-vendor sibling dossier
(TUF), and the pair-null dossier (3802->3810). The 16/09 dump lands
against measured profiles, and every deviation is diagnosable block by
block.

stdlib-only; read-only on every image it touches; precedent fw33/35/36/
37/38/39/40/41.
"""
import argparse
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RING = 42

STRENGTHS = ("set", "co", "blind", "identity")
COUPLINGS = ("aligned", "na", "confirmed", "bare", "blind", "identity")
IDENTITY_COUPLINGS = ("known-clean", "coherent-foreign", "suspicious",
                      "refused-contradiction")
PROFILES = ("clean", "stranger", "suspicious", "refused",
            "clean-pair", "event-pair")

# ------------------------------------------------------- the blind-spot map
# pid -> (axis, strength, reason).  Non-blind axes MUST be fw41 AXES
# (gate R2); blind rows carry the blind domain as the axis label plus a
# reason (gate R13) — the map is the instrument's design, validated
# against the live oracle register (gate R1) and frozen in the register.
AXIS_MAP = {
    "P-01": ("rom", "blind",
             "the detector reports rom_bytes but sizes carry no class"),
    "P-02": ("agesa", "set",
             "the agesa axis classifies the version token directly"),
    "P-03": ("agesa", "co",
             "the prefix travels inside the token the agesa axis "
             "extracts; a prefix-only swap is co-travel, not set proof"),
    "P-04": ("species", "set",
             "the armor quartet are genome species (born 3802)"),
    "P-05": ("species", "set",
             "SbRomArmorSmm is a genome species (born 3802)"),
    "P-06": ("whitelist", "set",
             "the chip-table axis diffs families both ways"),
    "P-07": ("smm", "set",
             "legacy SMM presence is a set phenomenon on the smm axis"),
    "P-08": ("species", "co",
             "a pure recount (same GUIDs, different count) is invisible "
             "to sets; count deviations usually co-travel with "
             "births/deaths"),
    "P-09": ("dsdt", "set",
             "the dsdt axis diffs checksum-valid DSDT variants"),
    "P-10": ("acpi-ssdt", "blind",
             "the dsdt universe tracks DSDT hashes only; AOD SSDT "
             "revisions leave no trace on it"),
    "P-11": ("certs", "set",
             "the certs axis diffs X.509 bodies against the DER "
             "universe"),
    "P-12": ("ifr", "blind",
             "no detector axis reads the setup facade"),
    "P-13": ("ifr", "blind",
             "no detector axis reads form-package validity"),
    "P-14": ("varstore", "blind",
             "no detector axis reads the factory Setup varstore"),
    "P-15": ("varstore", "blind",
             "never-asked bytes live only in lens territory"),
    "P-16": ("varstore", "blind",
             "the never-asked share is a varstore-derived ratio"),
    "P-17": ("smm", "set",
             "the smm axis diffs SMM-typed GUID sets"),
    "P-18": ("identity", "identity",
             "the H3 verdict IS the identity layer; the row rides on "
             "identity_coupling"),
    "P-19": ("psp", "blind",
             "no detector axis reads PSP bodies"),
    "P-20": ("agesa", "set",
             "the agesa axis carries the P-20 floor class"),
    "P-21": ("species", "set",
             "a third armor wave would surface as armor-species set "
             "changes"),
    "P-22": ("species", "set",
             "births/deaths are set phenomena on the species axis"),
    "P-23": ("certs", "set",
             "the certs axis diffs the DER trust set"),
    "P-24": ("ifr", "blind",
             "the facade floor is IFR territory"),
    "P-25": ("dsdt", "set",
             "the dsdt axis diffs checksum-valid DSDT variants"),
    "P-26": ("whitelist", "set",
             "the chip-table axis diffs families both ways"),
}


class Refusal(Exception):
    """L1/L2/L3 refusal — loud, claimed, exit 2."""


# ---------------------------------------------------------------- loading

def _load_mod(name):
    key = f"_{name}"
    if key not in _M:
        path = os.path.join(HERE, name + ".py")
        spec = importlib.util.spec_from_file_location(name, path)
        m = importlib.util.module_from_spec(spec)
        sys.modules[name] = m
        spec.loader.exec_module(m)
        _M[key] = m
    return _M[key]


def _mods():
    """(fw35, fw37, fw38, fw39, fw40, fw41) — the whole chain. fw42 sits
    on top, never instead."""
    return (_load_mod("fw35-oracle"), _load_mod("fw37-differ"),
            _load_mod("fw38-exam"), _load_mod("fw39-identity"),
            _load_mod("fw40-merge"), _load_mod("fw41-novelty"))


_M = {}

# --------------------------------------------------- the walk memoization
# fw39._deep_inventory is deterministic and read-only; the exam/identify/
# novelty chain used to walk the SAME image up to three times per process
# (identify's fingerprint, fw41's _deep, the pair's ledger walks). fw42
# installs ONE pure memoization (abspath-keyed) on the fw39 module so
# every consumer shares a single walk per image. Gate I7 counts the
# walks to prove the weld saved the passes.

_WALKS = {}
_UNIVERSES = None


def _universes():
    """The register-derived detector universes, built ONCE per process
    (build_universes walks all nine rungs — 160 s measured; the selftest
    and the CLI share the cache). Pure: the universes depend on the
    registers and the corpus, never on the image under reading."""
    global _UNIVERSES
    if _UNIVERSES is None:
        _UNIVERSES = f41_mod().build_universes(build_smm=True)
    return _UNIVERSES


def _install_walk_cache():
    f39 = _mods()[3]
    orig = f39._deep_inventory
    if getattr(orig, "_fw42_memo", False):
        return
    def memoized(image):
        key = os.path.abspath(image)
        if key not in _WALKS:
            _WALKS[key] = orig(image)
        return _WALKS[key]
    memoized._fw42_memo = True
    memoized._orig = orig
    f39._deep_inventory = memoized


def walk_count():
    return len(_WALKS)


# ---------------------------------------------------------- the coherence

def _axis_entries(nov):
    """Unregistered-entry count per detector axis (the evidence a miss
    can be confirmed with)."""
    return {
        "species": len(nov["species"].get("unregistered") or []),
        "certs": len(nov["certs"].get("unregistered") or []),
        "dsdt": len(nov["dsdt"].get("unregistered") or []),
        "agesa": 1 if nov["agesa"].get("class") == "unregistered" else 0,
        "whitelist": (len(nov["whitelist"].get("extra") or [])
                      + len(nov["whitelist"].get("missing") or [])),
        "smm": len(nov["smm"].get("unregistered") or []),
    }


def identity_coupling(verdict, unregistered_total):
    """L2 for the judge x detector pair. known-release + unregistered
    content is impossible by the coverage proof (fw41 I1/I2) — a
    refusal, not a class to interpret."""
    if verdict == "known-release":
        if unregistered_total == 0:
            return "known-clean"
        return "refused-contradiction"
    if unregistered_total > 0:
        return "coherent-foreign"
    return "suspicious"


def _pid(p):
    """Oracle.score yields (prediction_dict, verdict, note) — accept both
    the dict and a bare id (the welded rows vs the raw rows)."""
    return p["id"] if isinstance(p, dict) else p


def coupling_rows(score_rows, entries):
    """L2: every oracle row gets its coupling class through the
    blind-spot map. hit -> aligned; na -> na; miss/partial -> blind,
    confirmed (detector has entries on the row's axis), bare (no
    entries), or identity (P-18 rides on identity_coupling)."""
    out = []
    for p, v, _note in score_rows:
        pid = _pid(p)
        axis, strength, _reason = AXIS_MAP[pid]
        if v == "hit":
            c = "aligned"
        elif v == "na":
            c = "na"
        elif strength == "identity":
            c = "identity"
        elif strength == "blind":
            c = "blind"
        elif entries.get(axis, 0) > 0:
            c = "confirmed"
        else:
            c = "bare"
        out.append({"id": pid, "verdict": v, "axis": axis,
                    "strength": strength, "coupling": c})
    return out


def profile_of(identity_c, refuses):
    """L2: the claim-free profile. Refusals dominate; the H3 question is
    NOT a profile (it is the P-18 row + the identity verdict)."""
    if refuses:
        return "refused"
    if identity_c == "known-clean":
        return "clean"
    if identity_c == "suspicious":
        return "suspicious"
    return "stranger"


# ------------------------------------------------------- the dossier itself

def _check_image(image):
    if not image or not os.path.exists(image):
        raise Refusal(f"image not found: {image!r} — L1 refuses to "
                      "assemble a dossier on a reading that cannot run")
    if not os.path.isfile(image):
        raise Refusal(f"not a file: {image!r}")


def _ceilings():
    path = os.path.join(HERE, "vendor-scorelines.json")
    with open(path) as f:
        return json.load(f).get("ceilings") or {}


def dossier(image, lenses=None, target="day0", geometry=True,
            lens_wins=()):
    """The ONE day-0 command: readings 1+2 (exam+identify+weld+score via
    the fw40 weld, identify run ONCE) + reading 3 (fw41 novelty on the
    same image) + the coherence layer. Returns the dossier dict."""
    f35, _f37, f38, f39, f40, f41 = _mods()
    _install_walk_cache()
    _check_image(image)
    fw_target = "day0-3644" if target == "day0" else "release-41"

    examout, draft = f38.exam(image, target=fw_target, geometry=geometry)
    ident = f39.identify(image)
    merged, weld_report = f40.weld(draft, ident, lenses=lenses,
                                   target=target, lens_wins=lens_wins)
    rows, n = f35.Oracle().score(merged)
    nov = f41.novelty(image, _universes())

    return _assemble(image, target, ident, nov, rows, n, merged,
                     weld_report, examout)


def _assemble(image, target, ident, nov, rows, n, merged, weld_report,
              examout=None):
    verdict = ident["verdict"]["verdict"]
    un_total = nov["summary"]["unregistered_total"]
    ic = identity_coupling(verdict, un_total)
    entries = _axis_entries(nov)
    couples = coupling_rows(rows, entries)
    refuses = []
    if ic == "refused-contradiction":
        refuses.append(
            "L2/L3: identity says known-release (byte-identity under the "
            "registered sha convention) but the detector found "
            f"{un_total} unregistered finding(s) — instrument "
            "disagreement on a known rung; registers drifted or an "
            "extractor broke. Refusing to profile.")
    # L3 calibration: byte-identity forces the scoreline onto the
    # ceiling registered for that rung (where the scorelines register
    # carries one).
    ceiling_note = None
    if verdict == "known-release" and not refuses:
        matched = ident["verdict"].get("matched_release")
        ceilings = _ceilings()
        if isinstance(matched, str) and matched in ceilings:
            c = ceilings[matched]["counts"]
            if (n["hit"], n["partial"], n["miss"], n["na"]) != (
                    c["hit"], c["partial"], c["miss"], c["na"]):
                refuses.append(
                    f"L3: byte-identical to {matched} but the scoreline "
                    f"{n} deviates from the registered ceiling {c} — "
                    "instrument disagreement, refusing to profile.")
            else:
                ceiling_note = f"scoreline == {matched} ceiling"
        elif isinstance(matched, list):
            ceiling_note = (f"sha matches {matched}; multiple rungs "
                            "share the body sha — no single ceiling")
        else:
            ceiling_note = (f"byte-identical to {matched}; no ceiling "
                            "registered for that rung (extension lives "
                            "in vendor-dossier-register.json)")
    profile = profile_of(ic, refuses)
    hits = sorted(_pid(p) for p, v, _ in rows if v == "hit")
    d = {
        "instrument": "fw42-dossier", "ring": RING,
        "mode": "dossier", "image": image, "target": target,
        "rom": {"bytes": (examout or {}).get("rom", {}).get("bytes")
                if isinstance((examout or {}).get("rom"), dict) else None},
        "readings": {
            "oracle": {"instrument": "fw35-oracle", "ring": 35,
                       "via": "fw40 weld (exam 38 + identify 39)",
                       "counts": n,
                       "rows": [{"id": _pid(p), "verdict": v,
                                 "note": note} for p, v, note in rows]},
            "identity": {"instrument": "fw39-identity", "ring": 39,
                         "verdict": verdict,
                         "matched_release":
                             ident["verdict"].get("matched_release"),
                         "nearest_release":
                             ident["verdict"].get("nearest_release"),
                         "distinct_fingerprints_count":
                             ident["verdict"].get(
                                 "distinct_fingerprints_count"),
                         "note": ident["verdict"].get("note")},
            "novelty": {"instrument": "fw41-novelty", "ring": 41,
                        "summary": nov["summary"],
                        "axes": {ax: {k: nov[ax].get(k)
                                      for k in _NOVELTY_KEYS[ax]}
                                 for ax in f41_mod().AXES}},
        },
        "coherence": {
            "identity_coupling": ic,
            "coupling_rows": couples,
            "axis_entries": entries,
            "unregistered_total": un_total,
            "hit_set": hits,
            "refusals": refuses,
            "ceiling_note": ceiling_note,
            "profile": profile,
        },
        "weld_report": weld_report,
        "provenance": {"instrument": "fw42-dossier", "ring": RING,
                       "laws": ["L1 completeness", "L2 coherence",
                                "L3 calibration", "L4 separation"],
                       "readings": ["fw35+fw38+fw39+fw40 (welded)",
                                    "fw39-identity", "fw41-novelty"]},
    }
    return d, merged


def f41_mod():
    return _mods()[5]


_NOVELTY_KEYS = {
    "species": ["universe", "register_species", "observed", "known",
                "unregistered", "anticipated"],
    "certs": ["universe", "observed", "known", "unregistered"],
    "dsdt": ["universe", "observed", "known", "unregistered", "primary"],
    "agesa": ["level", "multiple", "class", "ladder_max", "floor41",
              "day0_envelope", "combo"],
    "whitelist": ["universe", "register", "extracted", "extra",
                  "missing"],
    "smm": ["universe", "observed", "known", "unregistered"],
}


# ----------------------------------------------------------- the pair mode

def dossier_pair(old, new):
    """The release-41 command: exam_pair + identify(new) + weld + score
    + novelty(new) + the pair coherence. Brand-new species are births
    that even the register universe cannot claim — the beyond-register
    event class."""
    f35, f37, f38, f39, f40, f41 = _mods()
    _install_walk_cache()
    _check_image(old)
    _check_image(new)
    examout, draft = f38.exam_pair(old, new)
    ident = f39.identify(new)
    merged, weld_report = f40.weld(draft, ident, lenses=None,
                                   target="release41")
    rows, n = f35.Oracle().score(merged)
    nov = f41.novelty(new, _universes())

    births = sorted(set(f37.Engine().inv(new)["modules"])
                    - set(f37.Engine().inv(old)["modules"]))
    deaths = sorted(set(f37.Engine().inv(old)["modules"])
                    - set(f37.Engine().inv(new)["modules"]))
    un_species = set(nov["species"].get("unregistered") or [])
    brand_new = sorted(set(births) & un_species)

    verdict = ident["verdict"]["verdict"]
    un_total = nov["summary"]["unregistered_total"]
    ic = identity_coupling(verdict, un_total)
    couples = coupling_rows(rows, _axis_entries(nov))
    refuses = []
    if ic == "refused-contradiction":
        refuses.append("L2/L3: the NEW image is byte-identical to a "
                       f"known release ({verdict}) yet carries "
                       f"{un_total} unregistered finding(s) — refusing.")
    if brand_new:
        coupling = "beyond-register-births"
    elif births or deaths:
        coupling = "registered-births"
    else:
        coupling = "clean-pair"
    profile = "refused" if refuses else (
        "clean-pair" if coupling == "clean-pair" else "event-pair")
    d = {
        "instrument": "fw42-dossier", "ring": RING,
        "mode": "dossier-pair", "old": old, "new": new,
        "target": "release41",
        "readings": {
            "oracle": {"instrument": "fw35-oracle", "ring": 35,
                       "counts": n,
                       "rows": [{"id": _pid(p), "verdict": v,
                                 "note": note} for p, v, note in rows]},
            "identity": {"instrument": "fw39-identity", "ring": 39,
                         "verdict": verdict,
                         "matched_release":
                             ident["verdict"].get("matched_release"),
                         "note": ident["verdict"].get("note")},
            "novelty": {"instrument": "fw41-novelty", "ring": 41,
                        "summary": nov["summary"]},
        },
        "pair_coherence": {
            "births": births, "deaths": deaths,
            "brand_new_species": brand_new,
            "coupling": coupling,
            "identity_coupling": ic,
            "coupling_rows": couples,
            "refusals": refuses,
            "profile": profile,
        },
        "weld_report": weld_report,
        "provenance": {"instrument": "fw42-dossier", "ring": RING,
                       "laws": ["L1 completeness", "L2 coherence",
                                "L3 calibration", "L4 separation"]},
    }
    return d, merged


# ------------------------------------------------------------ the register

def load_register():
    path = os.path.join(HERE, "vendor-dossier-register.json")
    with open(path) as f:
        return json.load(f)


def clean_record(d):
    """The compact per-rung record the register freezes (the clean
    dossier envelope)."""
    return {
        "image": os.path.basename(d["image"]),
        "verdict": d["readings"]["identity"]["verdict"],
        "matched_release": d["readings"]["identity"].get(
            "matched_release"),
        "counts": d["readings"]["oracle"]["counts"],
        "unregistered_total": d["coherence"]["unregistered_total"],
        "identity_coupling": d["coherence"]["identity_coupling"],
        "profile": d["coherence"]["profile"],
        "ceiling_note": d["coherence"].get("ceiling_note"),
    }


def rung_path(rung):
    f41 = f41_mod()
    if rung not in f41.RUNG_FILES:
        raise Refusal(f"unknown rung {rung!r} — known: "
                      f"{sorted(f41.RUNG_FILES)}")
    return os.path.join(f41.CORPUS, f41.RUNG_FILES[rung])


def clean(rung):
    """The live calibration target: the dossier of a known rung must be
    the clean profile."""
    return dossier(rung_path(rung), target="day0")


# ------------------------------------------------------------------ show

def show(d):
    print(json.dumps(d, indent=2))


def show_summary(d):
    if d.get("mode") == "dossier-pair":
        pc = d["pair_coherence"]
        print(f"profile={pc['profile']}  coupling={pc['coupling']}  "
              f"births={len(pc['births'])} deaths={len(pc['deaths'])} "
              f"brand_new={len(pc['brand_new_species'])}")
        print(f"identity={d['readings']['identity']['verdict']}  "
              f"novelty={d['readings']['novelty']['summary']}")
        print(f"counts={d['readings']['oracle']['counts']}")
        return
    c = d["coherence"]
    print(f"profile={c['profile']}  identity_coupling="
          f"{c['identity_coupling']}  unregistered="
          f"{c['unregistered_total']}")
    print(f"identity={d['readings']['identity']['verdict']}  "
          f"matched={d['readings']['identity'].get('matched_release')}  "
          f"counts={d['readings']['oracle']['counts']}")
    for r in c["coupling_rows"]:
        if r["coupling"] not in ("aligned", "na"):
            print(f"  {r['id']} {r['verdict']:8s} axis={r['axis']:11s} "
                  f"strength={r['strength']:8s} coupling={r['coupling']}")
    for msg in c["refusals"]:
        print(f"  REFUSAL: {msg}")


# --------------------------------------------------------------- selftest

class _G:
    """Gate ledger — the house style: numbered, named, counted, exit 2 on
    any failure."""

    def __init__(self):
        self.n = 0
        self.bad = []

    def gate(self, name, ok, info=""):
        self.n += 1
        tag = "PASS" if ok else "FAIL"
        print(f"  {tag}  {name}" + (f"  [{info}]" if info else ""))
        if not ok:
            self.bad.append(name)
        return ok

    def finish(self, label):
        print(f"fw42-dossier selftest: {self.n - len(self.bad)}/{self.n} "
              f"gates {'PASS' if not self.bad else 'FAIL'} ({label})")
        return 2 if self.bad else 0


def _poisoned_weld_refusal(f40, f38):
    """L4 echo: the weld under the dossier refuses mixed-key drafts
    (the fw40 separation law, re-verified through this instrument)."""
    keys = f38.template_keys()
    if not keys:
        return False, "fw38 template_keys unavailable"
    draft = {k: None for k in keys}
    draft["agesa_level"] = "1.2.0.6c"
    draft["agesa_level_41"] = "1.2.0.12"   # the poison: mixed targets
    try:
        f40.weld(draft, None, lenses=None, target="day0")
        return False, "mixed-key draft accepted (separation violated)"
    except f40.WeldError as e:
        return True, f"{e.kind if hasattr(e, 'kind') else 'weld'} refused"
    except Exception as e:                                   # noqa: BLE001
        return False, f"wrong refusal type: {type(e).__name__}"


def selftest(no_live=False):
    g = _G()
    f35, f37, f38, f39, f40, f41 = _mods()

    # ---------------- tier R — laws re-derived, corpus-free
    preds = f41._oracle_predictions()
    pids = [p["id"] for p in preds]
    g.gate("R1 axis_map covers exactly P-01..P-26",
           sorted(AXIS_MAP) == sorted(pids) and len(pids) == 26,
           f"{len(AXIS_MAP)} mapped / {len(pids)} registered")

    ok_ax, bad = True, []
    for pid, (ax, st, _r) in AXIS_MAP.items():
        if st == "blind":
            continue
        if st == "identity":
            if pid != "P-18":
                ok_ax, _ = False, bad.append(pid)
            continue
        if ax not in f41.AXES:
            ok_ax, _ = False, bad.append(pid)
    g.gate("R2 non-blind axes are fw41 axes; identity is P-18 alone",
           ok_ax and set(STRENGTHS) == {"set", "co", "blind", "identity"},
           f"bad={bad}")

    syn = [(pid, v, "") for pid in AXIS_MAP
           for v in ("hit", "na", "miss", "partial")]
    cs = {r["coupling"] for r in coupling_rows(syn, {})}
    g.gate("R3 coupling enum closed under the full sweep",
           cs <= set(COUPLINGS) and len(cs) == len(COUPLINGS) - 1,
           f"saw={sorted(cs)}")

    ic4 = [identity_coupling("known-release", 0),
           identity_coupling("known-release", 3),
           identity_coupling("no-match-h3-eligible", 3),
           identity_coupling("no-match-below-floor", 0)]
    g.gate("R4 identity coupling: four branches, one refusal",
           ic4 == ["known-clean", "refused-contradiction",
                   "coherent-foreign", "suspicious"], f"{ic4}")

    prof = [profile_of("known-clean", []),
            profile_of("coherent-foreign", []),
            profile_of("suspicious", []),
            profile_of("known-clean", ["x"])]
    g.gate("R5 profile derivation: clean/stranger/suspicious/refused",
           prof == ["clean", "stranger", "suspicious", "refused"]
           and set(PROFILES) == {"clean", "stranger", "suspicious",
                                 "refused", "clean-pair", "event-pair"},
           f"{prof}")

    ok_blind = all(isinstance(AXIS_MAP[p][2], str) and AXIS_MAP[p][2]
                   for p, (a, s, _r) in AXIS_MAP.items() if s == "blind")
    n_blind = sum(1 for _p, (_a, s, _r) in AXIS_MAP.items()
                  if s == "blind")
    g.gate("R6 every blind row carries its reason (the honest map)",
           ok_blind and n_blind == 9, f"blind={n_blind}/26")

    ok_sep, info = _poisoned_weld_refusal(f40, f38)
    g.gate("R7 L4 separation echo: the weld refuses mixed-key drafts",
           ok_sep, info)

    try:
        dossier("/nonexistent/image.rom")
        g.gate("R8 L1 refusal on a missing image", False, "no refusal")
    except Refusal:
        g.gate("R8 L1 refusal on a missing image", True)
    except Exception as e:                                   # noqa: BLE001
        g.gate("R8 L1 refusal on a missing image", False,
               f"wrong type: {type(e).__name__}")

    oracle = f35.Oracle()
    g.gate("R9 oracle register intact (26 predictions through the chain)",
           len(oracle.preds) == 26 and len(oracle.reg["predictions"]) == 26,
           f"{len(oracle.preds)} registered")

    try:
        reg = load_register()
        have_reg = True
    except FileNotFoundError:
        have_reg = False
    g.gate("R10 the dossier register exists (generated before freeze)",
           have_reg)

    if have_reg:
        am = reg.get("axis_map") or {}
        same = all(am.get(p, [None, None])[0] == v[0]
                   and am.get(p, [None, None])[1] == v[1]
                   for p, v in AXIS_MAP.items()) and len(am) == 26
        g.gate("R11 the frozen axis_map == the instrument map",
               same, f"{len(am)} rows")

        cd = reg.get("clean_dossiers") or {}
        ceil = _ceilings()
        ok_c = bool(cd) and all(
            v.get("profile") == "clean"
            and v.get("unregistered_total") == 0
            and v.get("verdict") == "known-release"
            for v in cd.values())
        ok_cc = all(
            (cd[r]["counts"]["hit"], cd[r]["counts"]["partial"],
             cd[r]["counts"]["miss"], cd[r]["counts"]["na"])
            == (ceil[r]["counts"]["hit"], ceil[r]["counts"]["partial"],
                ceil[r]["counts"]["miss"], ceil[r]["counts"]["na"])
            for r in cd if r in ceil)
        g.gate("R12 clean dossiers: 9/9 clean, ceilings agree with the "
               "scorelines register",
               ok_c and ok_cc and len(cd) == 9,
               f"{len(cd)} rungs, ceil-agree={ok_cc}")

        led = json.load(open(os.path.join(HERE,
                                          "vendor-novelty-ledger.json")))
        g.gate("R13 the two registers agree: zero-ledger empty AND every "
               "clean dossier at zero",
               led.get("entries") == [] and ok_c,
               f"ledger={len(led.get('entries') or [])}")

        fd = reg.get("foreign_dossier") or {}
        sd = reg.get("sibling_dossier") or {}
        pd = reg.get("pair_null_dossier") or {}
        g.gate("R14 stranger + sibling + pair-null frozen with measured "
               "profiles",
               fd.get("profile") == "stranger"
               and sd.get("profile") == "stranger"
               and pd.get("profile") == "clean-pair",
               f"foreign={fd.get('profile')} sibling={sd.get('profile')} "
               f"pair={pd.get('profile')}")
    else:
        for name in ("R11", "R12", "R13", "R14"):
            g.gate(name + " (register absent)", False, "register missing")

    if no_live:
        print("  SKIP tier I (--no-live): the live corpus readings are "
              "not exercised")
        return g.finish("tier R only (--no-live)")

    # ---------------- tier I — live corpus
    if not os.path.isdir(f41.CORPUS):
        print("  SKIP tier I (loud): corpus absent at " f"{f41.CORPUS}")
        return g.finish("tier R only (corpus absent)")

    _WALKS.clear()
    d36, _ = clean("3604")
    g.gate("I1 clean 3604: profile clean, zero unregistered, ceiling "
           "agrees",
           d36["coherence"]["profile"] == "clean"
           and d36["coherence"]["unregistered_total"] == 0
           and d36["coherence"]["identity_coupling"] == "known-clean"
           and d36["readings"]["oracle"]["counts"]
           == {"hit": 10, "partial": 1, "miss": 1, "na": 14},
           f"{d36['coherence']['profile']} "
           f"{d36['readings']['oracle']['counts']}")
    g.gate("I2 one deep walk serves exam+identify+novelty on 3604",
           walk_count() == 1, f"walks={walk_count()}")

    d46, _ = clean("4655")
    g.gate("I3 clean 4655: profile clean, zero unregistered",
           d46["coherence"]["profile"] == "clean"
           and d46["coherence"]["unregistered_total"] == 0,
           f"{d46['readings']['oracle']['counts']}")

    if have_reg:
        g.gate("I4 register freshness: live 3604 record == frozen record",
               clean_record(d36) == (reg.get("clean_dossiers") or {})
               .get("3604"), "roundtrip")
    else:
        g.gate("I4 register freshness", False, "register missing")

    povmf = f41.FOREIGN_FILES["ovmf"]
    if os.path.exists(povmf):
        dov, _ = dossier(povmf)
        g.gate("I5 OVMF stranger: coherent-foreign, novelty>=1, profile "
               "stranger",
               dov["coherence"]["identity_coupling"] == "coherent-foreign"
               and dov["coherence"]["unregistered_total"] >= 1
               and dov["coherence"]["profile"] == "stranger",
               f"un={dov['coherence']['unregistered_total']} "
               f"verdict={dov['readings']['identity']['verdict']}")
        g.gate("I6 OVMF stranger signature: the welded hit-set is exactly "
               "{P-04, P-05, P-18}",
               set(dov["coherence"]["hit_set"]) == {"P-04", "P-05",
                                                    "P-18"},
               f"hits={dov['coherence']['hit_set']}")
    else:
        g.gate("I5 OVMF stranger", False, "OVMF image missing")
        g.gate("I6 stranger signature", False, "OVMF image missing")

    ptuf = f41.FOREIGN_FILES["tuf"]
    if os.path.exists(ptuf):
        dt, _ = dossier(ptuf)
        tuf_diffs = (dt["readings"]["identity"]
                     .get("distinct_fingerprints_count"))
        g.gate("I7 TUF sibling: no-match + novelty>=1 -> coherent-foreign",
               dt["readings"]["identity"]["verdict"].startswith("no-match")
               and dt["coherence"]["unregistered_total"] >= 1
               and dt["coherence"]["identity_coupling"]
               == "coherent-foreign",
               f"un={dt['coherence']['unregistered_total']} "
               f"diffs={tuf_diffs}")
    else:
        g.gate("I7 TUF sibling", False, "TUF image missing")

    r38, r31 = rung_path("3802"), rung_path("3810")
    dp, _m = dossier_pair(r38, r31)
    pc = dp["pair_coherence"]
    p22 = next(r for r in dp["readings"]["oracle"]["rows"]
               if r["id"] == "P-22")
    g.gate("I8 pair null 3802->3810: clean-pair, births=0 deaths=0, "
           "P-22 hit, 3/2/21",
           pc["profile"] == "clean-pair" and not pc["births"]
           and not pc["deaths"] and p22["verdict"] == "hit"
           and dp["readings"]["oracle"]["counts"]
           == {"hit": 3, "partial": 0, "miss": 2, "na": 21},
           f"{pc['profile']} {dp['readings']['oracle']['counts']}")

    g.gate("I9 walk discipline: exactly one deep walk per distinct image "
           "across the whole live tier",
           walk_count() == 5, f"walks={walk_count()} "
           f"(3604,4655,ovmf,tuf,3810)")

    return g.finish("tier R + tier I live")


# ---------------------------------------------------------------- manifest

def manifest():
    print(json.dumps({
        "instrument": "fw42-dossier", "ring": RING,
        "provenance": "le dossier — the triptych machine (the fourth "
                      "weld): the third reading (fw41) ran BESIDE the "
                      "chain; nothing confronted the three readings with "
                      "each other. fw42 welds oracle+judge+detector into "
                      "ONE dossier and adds the coherence layer: the "
                      "blind-spot map, the coupling classes, the identity "
                      "couplings, the claim-free profiles.",
        "modes": ["dossier <image> [--target day0|release41] [--lenses "
                  "file] [--lens-wins k..] [--out file]",
                  "dossier-pair <old> <new> [--out file]",
                  "clean <rung>", "register", "selftest [--no-live]",
                  "manifest"],
        "laws": {
            "L1": "completeness — every reading present and stamped; a "
                  "missing reading is a loud refusal (exit 2)",
            "L2": "coherence — every non-hit oracle row coupled to the "
                  "detector through the blind-spot map; identity x "
                  "detector coupling named; contradiction = refusal",
            "L3": "calibration — byte-identity forces the scoreline onto "
                  "the registered ceiling; the clean profile is the "
                  "16/09 calibration target",
            "L4": "separation — day-0 and release-41 never mix (the fw40 "
                  "law, echoed)",
        },
        "blind_spot_map": {"set": 14, "co": 2, "blind": 9,
                           "identity": 1},
        "register": "lab/vendor-dossier-register.json (blind-spot map + "
                    "9 clean dossiers + foreign + sibling + pair-null)",
    }, indent=2))
    return 0


# -------------------------------------------------------------------- main

def main(argv=None):
    ap = argparse.ArgumentParser(prog="fw42-dossier")
    ap.add_argument("mode", choices=["dossier", "dossier-pair", "clean",
                                     "register", "selftest", "manifest"])
    ap.add_argument("args", nargs="*")
    ap.add_argument("--target", choices=["day0", "release41"],
                    default="day0")
    ap.add_argument("--lenses")
    ap.add_argument("--lens-wins", nargs="*", default=[])
    ap.add_argument("--out")
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--no-live", action="store_true")
    a = ap.parse_args(argv)

    if a.mode == "manifest":
        return manifest()
    if a.mode == "selftest":
        return selftest(no_live=a.no_live)
    if a.mode == "register":
        show(load_register())
        return 0

    try:
        if a.mode == "dossier":
            if not a.args:
                print("dossier <image>", file=sys.stderr)
                return 2
            lenses = None
            if a.lenses:
                with open(a.lenses) as f:
                    lenses = json.load(f)
            d, merged = dossier(a.args[0], lenses=lenses, target=a.target,
                                lens_wins=a.lens_wins)
        elif a.mode == "dossier-pair":
            if len(a.args) < 2:
                print("dossier-pair <old> <new>", file=sys.stderr)
                return 2
            d, merged = dossier_pair(a.args[0], a.args[1])
        else:  # clean
            if not a.args:
                print("clean <rung>", file=sys.stderr)
                return 2
            d, merged = clean(a.args[0])
    except Refusal as e:
        print(f"REFUSAL: {e}", file=sys.stderr)
        return 2

    if a.out:
        with open(a.out, "w", encoding="utf-8") as f:
            json.dump({"dossier": d, "findings": merged}, f, indent=2)
        print(f"written: {a.out}")
    if a.quiet:
        show_summary(d)
    else:
        show(d)
    return 0


if __name__ == "__main__":
    sys.exit(main())
